routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/vueHome', function () {
//     return view('welcome');
// });

Auth::routes();
Route::get('/script','pos\ScriptController@index');
Route::get('/user/login','Auth\UserLoginController@showLoginForm')->name('user.login');
Route::post('/user/submit','Auth\UserLoginController@login')->name('user.login.submit');
Route::get('user/logout','Auth\UserLoginController@logout')->name('user.logout');

Route::get('auto-logout-action', 'MasterController@autoLogOutAction')->name('autoLogOutAction');
Route::group(['middleware' => 'auth.user'], function () {
	Route::get('/','MasterController@posIndex')->name('pos.home');
});
Route::get('jsBaseURLs', 'AdapterController@jsBaseURLs')->name('jsBaseURLs');
// pos
Route::group(['middleware' => ['auth.user'],'prefix' => 'pos', 'as'=>'pos.'], function (){
	Route::get('/', 'MasterController@posIndex')->name('home');
	Route::get('jsBaseURLs', 'AdapterController@posJsBaseURLs')->name('jsBaseURLs');
	Route::get('home', 'MasterController@home');
	Route::get('/getmenu','MasterController@getUserMenuList');
	Route::group(['namespace' => 'pos'], function (){
		posRoute();
	});
	//reportRoute();
});

// Admin
Route::get('/admin/','AdminHomeController@index')->name('admin.home');
Route::get('/admin/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/submit','Auth\AdminLoginController@login')->name('admin.login.submit');
Route::post('admin/logout','Auth\AdminLoginController@logout')->name('admin.logout');
Route::group(['middleware' => ['auth.admin'],'prefix' => 'admin', 'as'=>'admin.'], function(){
	Route::get('jsBaseURLs', 'AdapterController@adminJsBaseURLs')->name('jsBaseURLs');
	Route::group(['namespace' => 'admin'], function (){
		Route::get('/list','AdminController@index');
		Route::post('/add','AdminController@store');
		Route::get('/create','AdminController@create');
		Route::delete('delete/{id}','AdminController@destroy');
		Route::get('edit/{id}','AdminController@show');
		Route::get('/create/role','UserRoleController@create');
		Route::get('/create/adminrole','AdminRoleCocntroller@create');
		Route::get('/role/list','UserRoleController@index');
		Route::get('/adminrole/list','AdminRoleCocntroller@index');
		Route::post('/add/role','UserRoleController@store');
		Route::post('/add/adminrole','AdminRoleCocntroller@store');
		Route::get('/role/edit/{id}','UserRoleController@show');
		Route::get('/adminrole/edit/{id}','AdminRoleCocntroller@show');
		Route::delete('/role/delete/{id}','UserRoleController@destroy');
		Route::delete('/adminrole/delete/{id}','AdminRoleCocntroller@destroy');
		Route::get('/menu/list','MenuController@index');
		Route::post('/add/menu','MenuController@store');
		Route::get('/create/menu','MenuController@create');
		Route::get('/edit/menu/{id}','MenuController@show');
		Route::get('/getmenu','MenuController@getAdminMenuList');
		Route::delete('/delete/menu/{id}','MenuController@destroy');
		Route::post('/passwordchange','ChangePasswordController@passwordChange');
		Route::get('/user/list','UserController@index');
		Route::post('/user/add','UserController@store');
		Route::get('/user/create','UserController@create');
		Route::delete('/user/delete/{id}','UserController@destroy');
		Route::get('/user/edit/{id}','UserController@show');

		// Sales person
		Route::get('/salesPerson','SalesPersonController@index');
		Route::get('/salesPerson/create','SalesPersonController@create');
		Route::post('/salesPerson/add','SalesPersonController@store');
		Route::get('/salesPerson/edit/{id}','SalesPersonController@edit');
		Route::delete('/salesPerson/delete/{id}','SalesPersonController@destroy');
		//vndor
		Route::get('/vendor/list','VendorController@index');
		Route::get('/create/vendor','VendorController@create');
		Route::post('/add/vendor','VendorController@store');
		Route::get('/edit/vendor/{id}','VendorController@edit');
		Route::delete('/delete/vendor/{id}','VendorController@destroy');
		//customer info
		Route::get('/customerinfo/list','CompanyConfigurController@index');
		Route::get('/create/customerinfo','CompanyConfigurController@create');
		Route::post('/add/customerinfo','CompanyConfigurController@store');
		Route::get('/edit/customerinfo/{id}','CompanyConfigurController@edit');
		Route::delete('/delete/customerinfo/{id}','CompanyConfigurController@destroy');
		Route::get('/dashboard_data','DashboardController@index');
	});
});

function posRoute() {
	// Inventory Category
	Route::get('/inventory_category/list','InventoryCategoryController@index');
	Route::get('/inventory_category/create','InventoryCategoryController@create');
	Route::post('/inventory_category/add','InventoryCategoryController@store');
	Route::get('/inventory_category/edit/{id}','InventoryCategoryController@edit');
	Route::delete('/inventory_category/delete/{id}','InventoryCategoryController@destroy');
	// Inventory Item
	Route::get('/inventory_item/list','InventoryItemController@index');
	Route::get('/inventory_item/create','InventoryItemController@create');
	Route::post('/inventory_item/add','InventoryItemController@store');
	Route::get('/inventory_item/edit/{id}','InventoryItemController@edit');
	Route::delete('/inventory_item/delete/{id}','InventoryItemController@destroy');
	// Inventory Receive
	Route::get('/inventory_receive/list','InventoryReceiveController@index');
	Route::get('/inventory_receive/create','InventoryReceiveController@create');
	Route::post('/inventory_receive/add','InventoryReceiveController@store');
	Route::get('/inventory_receive/edit/{id}','InventoryReceiveController@edit');
	Route::delete('/inventory_receive/delete/{id}','InventoryReceiveController@destroy');
	Route::get('/inventory_receive/view','InventoryReceiveController@view');
	//vendor
	Route::get('/vendor/list','VendorController@index');
	Route::get('/create/vendor','VendorController@create');
	Route::post('/add/vendor','VendorController@store');
	Route::get('/edit/vendor/{id}','VendorController@edit');
	Route::delete('/delete/vendor/{id}','VendorController@destroy');
	//customer
	Route::get('/customer/list','customerController@index');
	Route::get('/create/customer','customerController@create');
	Route::post('/add/customer','customerController@store');
	Route::get('/edit/customer/{id}','customerController@edit');
	Route::delete('/delete/customer/{id}','customerController@destroy');

	Route::get('/pos/list','InventoryPosController@index');
	Route::get('pos/create','InventoryPosController@create');
	Route::post('/pos/add','InventoryPosController@store');
	Route::get('/pos/pos_data','InventoryPosController@posValue');
	Route::get('/invoicehistory/pos/pos_data','InventoryPosController@posValue');

  	Route::get('/view_statement/list','InventoryArViewController@index');
  	Route::get('/view_statement/edit/{id}','InventoryArViewController@edit');
  	Route::get('/post_ar_view_statement/edit/{id}','InventoryArViewController@post_ar_view_statement');
	Route::get('/post_ar_payment/list','InventoryArPostController@index');
	Route::post('/post_ar_payment/edit','InventoryArPostController@edit');
	//Inventory Report
	Route::get('/geilist','ItemReportController@create');
	Route::get('/geilist/report','ItemReportController@itemList');
	Route::get('/bestseller/report','ItemReportController@bestSeller');
	Route::get('/worstseller/report','ItemReportController@worstSeller');
	Route::get('/itemorder/report','ItemReportController@intemOnOrder');
	Route::get('/belowreorder/report','ItemReportController@itemBelowReorder');
	Route::get('/pricelist/report','ItemReportController@pricelist');
	Route::get('/physicalinventory/report','ItemReportController@physicalInventory');
	Route::get('/valuebycatogory/report','ItemReportController@itemValueByCategory');
	Route::get('/valuebyvendor/report','ItemReportController@itemValueByVendor');
	Route::get('/invetorysales/report','ItemReportController@iventorySales');
	Route::get('/invoicehistory/report','ItemReportController@invoiceHistory');
	Route::get('/accounts-income/report','AccountsReportController@incomeReport');
	Route::get('/accounts-paytype/report','AccountsReportController@paymentType');
	Route::get('/sales-tex/report','AccountsReportController@salesTex');
	Route::get('/account-summery/report','AccountsReportController@accountSummery');
	Route::get('/account-information/report','AccountsReportController@accountingInformationReport');
	Route::get('/ar-asing/report','ItemReportController@arAsingReport');
	//Inventory Report
	//customer report
	Route::get('/customer/report','CustomerReportController@customerList');
	//customer report
	//vendor report
	Route::get('/vendor/report','VendorReportController@vendorList');
	//vendor report
	//salesperson report
	Route::get('/getsalespersons/report','SlaespersonReportController@index');
	Route::get('/salesperson/report','SlaespersonReportController@salespersonList');
	Route::get('/salespersonsales/report','SlaespersonReportController@getSalesperson');
	//salesperson report
	Route::get('/dashboard_data','DashboardController@index');
}

Route::group(['middleware' => ['auth.user'],'prefix' => 'user', 'namespace' => 'user'], function(){
	Route::post('/passwordchange','ChangePasswordController@passwordChange');
	Route::get('/passwordchangeForm','ChangePasswordController@changePasswordView')->name('changePasswor');
	Route::post('/passwordchangeAction','ChangePasswordController@passwordChangeAction')->name('changePassworAction');
});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/pos/CustomerReportController.php
<?php

namespace App\Http\Controllers\pos;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Customer;
use Auth;

class CustomerReportController extends Controller
{

	public function index(Request $request)
    {

    }

    public function customerList(Request $request){
        
        $order = $request->input('item_value');
        $data['shorting_name'] = $request->input('shorting_name');
        $data['report_name'] = "Customer List";
        $data['report_title'] = "Customer Report";
        $data['reportDate'] = date('F d, Y');

        $data['reports_result'] = Customer::valid()->orderBy($order,'asc')->get();
        return view('report.customer-report',$data);
    }

    public function create()
    {
    }
    
    public function store(Request $request)
    {
        
    }

    public function edit(Request $request)
    {

    }

    public function destroy(Request $request)
    {
    

    }
    
    
}

app/Http/Controllers/pos/DashboardController.php
<?php

namespace App\Http\Controllers\pos;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\InventoryItemModel;
use App\Model\InventoryPosModel;
use App\Model\InventoryPosDetailsModel;
use App\Model\InventoryCategoryModel;
use App\Model\CompanyConfigur;
use App\Model\Customer;
use App\Model\Vendor;
use Auth;
use DB;

class DashboardController extends Controller
{

	public function index(Request $request)
    {
			 // DB::enableQueryLog();
			 //date according to date get data
			 $date_get=date('Y-m-d');
			 $year_start=date('Y').'-'.'01'.'-'.'01';
			 $monthly_start=date('Y').'-'.date('m').'-'.'01';

			 $pos_details_data=InventoryPosDetailsModel::join('inv_product','inv_product.id','=','inv_pos_details.product_id')
					->select(DB::raw('inv_pos_details.product_price * inv_pos_details.product_qty + (inv_pos_details.product_price *(inv_pos_details.product_tax/100)) * inv_pos_details.product_qty  as sale_total'),'inv_pos_details.date','inv_pos_details.product_id',DB::raw('inv_product.last_cost* inv_pos_details.product_qty +inv_pos_details.product_discount as last_purchase_total'),DB::raw('inv_product.avg_cost * inv_pos_details.product_qty+inv_pos_details.product_discount as avg_purchase_total'))
					->whereBetween('date',[$year_start,$date_get])
					->get();
 		 	 $pos_all_data=InventoryPosModel::whereBetween('date',[$year_start,$date_get])->get();
			 $this_year_sale=collect($pos_details_data)->pluck('product_id');
			 $sale_product=InventoryItemModel::whereIn('id',$this_year_sale)->get();
			 $configure_data=CompanyConfigur::where('id',1)->first();
			 //daily sale data
			 $daily_sell_product=collect($pos_details_data)->where('date',$date_get)->sum('sale_total');
			 if($daily_sell_product>0){
					$data['daily_sale']=$daily_sell_product;
			 }
			 else{
					$data['daily_sale']=0;
				}

			 //monthly sale
			 $monthly_sell_product=collect($pos_details_data)->whereBetween('date',[$monthly_start,$date_get])->sum('sale_total');
			 if($monthly_sell_product>0){
					$data['monthly_sale']=$monthly_sell_product;
			}
			else{
					$data['monthly_sale']=0;
			 }
			 //yearly Sale
			 $yearly_sell_product=collect($pos_details_data)->sum('sale_total');
			 if($yearly_sell_product>0) {
				 $data['yearly_sale']=$yearly_sell_product;

			 }
			 else {
			  $data['yearly_sale']=0;
			 }

       //cash account Sale
				$data['cash_sale']=collect($pos_all_data)->where('customer_name','==',null)->sum('sub_total');
				$data['receivable']=collect($pos_all_data)->where('customer_name','!==',null)->sum('sub_total');

			//profit loss
      $month_date=date('m');
			$profit=[];
			$loss=[];

			for($i=1;$i<=$month_date;$i++)
			{
				$month_start_date=date('Y').'-'.'0'.$i.'-'.'01';
				$month_end_date=date("Y-m-t", strtotime($month_start_date));
				$total_revenue=collect($pos_details_data)->whereBetween('date',[$month_start_date,$month_end_date])
																										 ->sum('sale_total');
				if($configure_data->calculate_profit_type=1){
          $purchase_total=collect($pos_details_data)->whereBetween('date',[$month_start_date,$month_end_date])
                                                      		->sum('last_purchase_total');

        }
        else {
          $purchase_total=collect($pos_details_data)->whereBetween('date',[$month_start_date,$month_end_date])
                                                       ->sum('avg_purchase_total');
        }
			  $loss_profit_total=($total_revenue - $purchase_total);

				$m=date('m',strtotime($month_start_date));
			  $d=date('d',strtotime($month_start_date));
				$y=date('Y',strtotime($month_start_date));
				$incremnt=$i-1;
				if($loss_profit_total>0){
					$profit[$i]=['amount'=>$loss_profit_total,'m'=>$m,'d'=>$d,'y'=>$y,'increment'=>$incremnt];
					$loss[$i]=['amount'=>0,'m'=>$m,'d'=>$d,'y'=>$y,'increment'=>$incremnt];
				}
				else {
					$loss[$i]=['amount'=>abs($loss_profit_total),'m'=>$m,'d'=>$d,'y'=>$y,'increment'=>$incremnt];
					$profit[$i]=['amount'=>0,'m'=>$m,'d'=>$d,'y'=>$y,'increment'=>$incremnt];
				}


			}

			$data['profit']=$profit;
			$data['loss']=$loss;
			 //first block all total data
			 $data['daily_sale']=$daily_sell_product;
			 $data['total_sold_item']=collect($sale_product)->sum('total_sold_c');
			 $data['total_category']=count(InventoryCategoryModel::all());
			 $data['total_vendor']=count(Vendor::all());
			 $data['total_product']=InventoryItemModel::valid()->select(DB::raw('IFNULL(sum(qty_hand),0) as totalQty'))->first()->totalQty;
			 $data['monthly_sale']=$monthly_sell_product;
			 $data['total_sale']=collect($sale_product)->sum('total_revenue_c');
			 $data['total_profit']=collect($sale_product)->sum('total_profit_c');
			 $data['best_seller']=InventoryPosDetailsModel::valid()
                    ->select('inv_product.inv_product_name','inv_pos_details.product_id', DB::raw('IFNULL(SUM(inv_pos_details.product_qty),0) as total_sold_c'))
                    ->join('inv_product', 'inv_pos_details.product_id', '=', 'inv_product.id')
                    ->whereBetween('date',[$year_start,$date_get])
                    ->orderBy('total_sold_c','desc')->groupBy('product_id')->limit(10)->get();
			$data['worst_seller']=InventoryPosDetailsModel::valid()
                    ->select('inv_product.inv_product_name','inv_pos_details.product_id', DB::raw('IFNULL(SUM(inv_pos_details.product_qty),0) as total_sold_c'))
                    ->join('inv_product', 'inv_pos_details.product_id', '=', 'inv_product.id')
                    ->whereBetween('date',[$year_start,$date_get])
                    ->orderBy('total_sold_c','asc')->groupBy('product_id')->limit(10)->get();

            $data['sell_by_category']=InventoryPosDetailsModel::valid()
                    ->select('inv_product_category.category_name','inv_product.category_id', DB::raw('IFNULL(SUM(inv_pos_details.product_qty),0) as total_sold'))
                    ->join('inv_product', 'inv_pos_details.product_id', '=', 'inv_product.id')
                    ->join('inv_product_category', 'inv_product.category_id', '=', 'inv_product_category.id')
                    ->whereBetween('date',[$year_start,$date_get])
                    ->orderBy('total_sold','desc')->groupBy('category_id')->limit(5)->get();

			 $data['dashboard_data']=1;

			 // print_r(DB::getQueryLog());


       return response()->json($data);
    }



    public function create()
    {
    }

    public function store(Request $request)
    {

    }

    public function edit(Request $request)
    {

    }

    public function destroy(Request $request)
    {


    }


}

resources/views/pos/app.blade.php
@include('includs.posHeader')
<style>
    .modal-backdrop{
        z-index: 999;
    }
    .modal-btn-wraper{
        overflow: hidden;
    }
    .modal-btn-wraper a{
        margin-left: 10px;
    }
    .modal-header h4{
        display: inline-block;
    }
</style>
<body>

    <!-- Header -->
    <div id="app">

        <header class="header navbar navbar-fixed-top" role="banner">
            <!-- Top Navigation Bar -->
            <div class="container">

                <!-- Only visible on smartphones, menu toggle -->
                <ul class="nav navbar-nav">
                    <li class="nav-toggle"><a href="javascript:void(0);" title=""><i class="icon-reorder"></i></a></li>
                </ul>

                <!-- Logo -->
                <a class="navbar-brand" href="{{ url('pos/') }}">
                    <img src="{{asset('melon/assets/img/logo.png')}}" alt="logo" />
                    POS
                </a>
                <!-- /logo -->
                <!-- Sidebar Toggler -->
                <a href="#" class="toggle-sidebar bs-tooltip" data-placement="bottom" data-original-title="Toggle navigation">
                    <i class="icon-reorder"></i>
                </a>
                <!-- /Sidebar Toggler -->
                <pos-topbar></pos-topbar>
                <!-- Top Right Menu -->
                <ul class="nav navbar-nav navbar-right">


                    <!-- User Login Dropdown -->
                    <li class="dropdown user user-layout" id="set-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!--<img alt="" src="assets/img/avatar1_small.jpg" />-->
                            <div class="profile-img">
                                <img src="{{asset('images/default.png')}}">
                                <span class="username">{{$user->name}}</span>
                                <i class="icon-caret-down small"></i>
                            </div>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="pages_user_profile.html"><i class="icon-user"></i> My Profile</a></li>
                            <li>
                                <pos-header-link></pos-header-link>
                            </li>
                            @if(Auth::guard('user')->user()->role_id == 1)
                                <li><a href="" data-toggle="modal" data-target="#shiftModal"><i class="icon-key"></i> Log Out</a>
                                </li>
                            @else
                                <li><a href="" onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();"><i class="icon-key"></i> Log Out</a>
                                </li>
                            @endif
                        </ul>
                        <form id="logout-form" action="{{ route('user.logout') }}" method="GET" style="display: none;">
                            @csrf
                        </form>
                    </li>
                    <!-- /user login dropdown -->
                </ul>
                <!-- /Top Right Menu -->
                <div class="modal fade" id="shiftModal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        
                          <!-- Modal Header -->
                          <div class="modal-header">
                            <h4 class="modal-title">Shifting Close</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                          </div>
                          
                          <!-- Modal body -->
                          <div class="modal-body">
                            <h4>Do you want to close your shift</h4>
                            <div class="modal-btn-wraper">
                                <a href="user/logout?shift_close=0&id={{$user->id}}" class="btn btn-danger pull-right">No</a>
                                <a href="user/logout?shift_close=1&id={{$user->id}}" class="btn btn-primary pull-right">Yes</a>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /top navigation bar -->
        </header> <!-- /.header -->

        <div id="container">
            <div id="sidebar" class="sidebar-fixed">
                <div id="sidebar-content">

                    <!-- Search Input -->
                        <!-- <form class="sidebar-search">

                            <div class="input-box">
                                <button type="submit" class="submit">
                                    <i class="icon-search"></i>
                                </button>
                                <span>
                                    <input type="text" placeholder="Search...">
                                </span>
                            </div>

                        </form> -->
                    <!-- Search Results -->

                    <div class="sidebar-search-results">

                        <i class="icon-remove close"></i>
                        <!-- Documents -->
                        <div class="title">
                            Documents
                        </div>
                        <ul class="notifications">
                            <li>
                                <a href="javascript:void(0);">
                                    <div class="col-left">
                                        <span class="label label-info"><i class="icon-file-text"></i></span>
                                    </div>
                                    <div class="col-right with-margin">
                                        <span class="message"><strong>John Doe</strong> received $1.527,32</span>
                                        <span class="time">finances.xls</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);">
                                    <div class="col-left">
                                        <span class="label label-success"><i class="icon-file-text"></i></span>
                                    </div>
                                    <div class="col-right with-margin">
                                        <span class="message">My name is <strong>John Doe</strong> ...</span>
                                        <span class="time">briefing.docx</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <!-- /Documents -->
                        <!-- Persons -->
                        <div class="title">
                            Persons
                        </div>
                        <ul class="notifications">
                            <li>
                                <a href="javascript:void(0);">
                                    <div class="col-left">
                                        <span class="label label-danger"><i class="icon-female"></i></span>
                                    </div>
                                    <div class="col-right with-margin">
                                        <span class="message">Jane <strong>Doe</strong></span>
                                        <span class="time">21 years old</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div> <!-- /.sidebar-search-results -->

                    <!--=== Navigation ===-->

                    <pos-sidebar></pos-sidebar>

                </div>
                <div id="divider" class="resizeable"></div>
            </div>
            <!-- /Sidebar -->

            <div id="content">
                <div class="container">
                    <!-- Breadcrumbs line -->
                   <!--  <div class="crumbs">
                        <ul id="breadcrumbs" class="breadcrumb">
                            <li>
                                <i class="icon-home"></i>
                                <a href="index.html">Dashboard</a>
                            </li>
                            <li class="current">
                                <a href="pages_calendar.html" title="">Calendar</a>
                            </li>
                        </ul>
                    </div> -->
                    <bredcrumb></bredcrumb>
                    <!-- /Breadcrumbs line -->
                    <!--=== Page Content ===-->
                <div class="row">
                    <router-view></router-view>
                </div>
                <!-- /Page Content -->
            </div>
                <!-- /.container -->
            </div>
        </div>

 </div>
    <script src="<?php echo url(route('pos.jsBaseURLs')); ?>"></script>
    <script src="{{asset('js/app.js')}}"></script>
@include('includs.posFooter')
</body>
</html>